site_name: ThaiOML (Open Medical Library of Thailand)
site_url: https://www.thaioml.org
site_description: Community-maintained, expert-reviewed medical education database.

repo_name: App & Settings
repo_url: http://localhost:3000
repo_icon: material/cog

plugins:
  - search
  - thaioml-linker

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: leuko
      primary: custom
      accent: custom
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: darkroom
      primary: custom
      accent: custom
    # Palette toggle for progressnote mode
    - scheme: progressnote
      primary: custom
      accent: custom
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/custom-theme.css



extra_javascript:
  - javascripts/theme-accent.js
  - javascripts/clerk-auth.js

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
