[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sira Pornsiriprasert", email = "code@psira.me" }
]
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.5.0",
    "thaioml-linker",
]

[project.scripts]
docs = "docs:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "plugins/thaioml_linker",
]

[tool.uv.sources]
thaioml-linker = { workspace = true }
