name: Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: true

      - name: Install root dependencies
        run: npm install

      - name: Install webapp dependencies
        run: cd webapp && npm install

      - name: Install backend dependencies
        run: cd backend && uv sync

      - name: Run Backend Unit Tests
        run: cd backend && uv run pytest

      - name: Run Webapp Unit Tests
        run: cd webapp && npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start Services
        run: |
          cd docs && npm install && uv sync && (uv run mkdocs serve &)
          cd backend && (uv run uvicorn backend.main:app --port 8080 &)
          cd webapp && (npm run dev &)
          npx decap-server &
          
          # Wait for services to be ready
          npx wait-on http-get://localhost:8000
          npx wait-on http-get://localhost:3000
          npx wait-on http-get://localhost:8080
          npx wait-on http-get://localhost:8081/api/v1

      - name: Run Playwright E2E Tests
        run: npx playwright test --project=chromium
